de\chilan\WebsiteBundle\Entity\Namensliste:
    type: entity
    table: namensliste
    id:
        namenid:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: NamenID
            generator:
                strategy: IDENTITY
    fields:
        vorname:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            column: Vorname
        name:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            column: Name
        website:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
            column: Website
        email:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
            column: EMail
    lifecycleCallbacks: {  }
