de\chilan\WebsiteBundle\Entity\UserData:
    type: entity
    table: user_data
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: ID
            generator:
                strategy: IDENTITY
    fields:
        namenid:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: NamenID
        email:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
            column: EMail
        sprache:
            type: string
            nullable: false
            length: 4
            options:
                fixed: false
                default: de
            column: Sprache
        passwort:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
            column: Passwort
        regdatum:
            type: datetime
            nullable: false
            column: RegDatum
        rechte:
            type: string
            nullable: false
            length: 37
            options:
                fixed: false
                default: '0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0'
            column: Rechte
        inaktivBit:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: Inaktiv_bit
        newsletter:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: Newsletter
        echanges:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
            column: EChanges
        nchanges:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: NChanges
        mailsend:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: Mailsend
        loginTime:
            type: datetime
            nullable: false
            column: login_time
        secureKey:
            type: string
            nullable: false
            length: 32
            options:
                fixed: false
                default: 'no'
            column: secure_key
        ipAdress:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
                default: 0.0.0.0
            column: ip_adress
    lifecycleCallbacks: {  }
