root:
    path: /
    defaults:
        _controller: WebsiteBundle:Page:index
        path: /%locale%/
        permanent: true
_app:
  resource: "@WebsiteBundle/Resources/config/routing/routing.yml"
  prefix:   /{_locale}
  requirements:
    _locale: de|en
  defaults: { _locale: de}
