_main:
    resource: "@WebsiteBundle/Controller/PageController.php"
    type:     annotation
_gallery:
    resource: "@WebsiteBundle/Controller/Gallery/GalleryController.php"
    type:     annotation
    prefix: /galerie
_picture:
    resource: "@WebsiteBundle/Controller/Gallery/PictureController.php"
    type:     annotation
    prefix: /picture
_news:
    resource: "@WebsiteBundle/Controller/Blog/NewsController.php"
    type:     annotation
    prefix: /news